apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis-vpa
spec:
  tragetRef:
    apiVersion: "apps/v1"
    kind: Deployment 
    name: redis
  updatePolicy:
    updateMode: "Auto"