apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment 
    name: redis
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: redis 
        minAllowed: 
          cpu: "200m"
          memory: "500Mi"
        maxAllowed:
          cpu: "1" 
          memory: "2Gi"
        controlledResources: ["cpu","memory"]
