name: Deploy reddis on GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ia-generation-5
  GKE_CLUSTER: futurandco
  GKE_ZONE: europe-west9

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          python-version: '3.8'

      - name: Install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Deploy to GKE
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "${GCP_CREDENTIALS}" > /tmp/keyfile.json
          gcloud auth activate-service-account --key-file=/tmp/keyfile.json
          cat /tmp/keyfile.json
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }} --project ${{ env.PROJECT_ID }}
          chmod +x redis-pvc.sh
          ./redis-pvc.sh
          kubectl apply -f redis-deployment.yaml
          kubectl apply -f redis-service.yaml
          kubectl apply -f redis-vpa.yaml
